### ISSUE TITLE
bilibili resolving problem

### ISSUE THREAD

**Issue by fredhdx** [knightReigh/loadercdn-downloader#1]
There are currently problems using bilibli.com urls. Part of the problem is with loadercdn; another has to deal with bilibili recently re-designed its html structure. 

The author is trying to fix it.

**Comment by TheHatMan98** [comment]
No sound when i download https://www.dplay.se/videos/superspararna/superspararna-101 ?

**Comment by fredhdx** [comment]
Parsing fixed. But server does not support muti-part videos and .flv downloads.
