### ISSUE TITLE
Dplay.se

### ISSUE THREAD

**Issue by Jujudo** [knightReigh/loadercdn-downloader#2]
No sound when i download https://www.dplay.se/videos/superspararna/superspararna-101 ?

**Comment by fredhdx** [comment]
I tested your site with loadercdn's direct web console. The extracted audio link will not work, returning 
```
It seems that the file has no audio stream. Please try a video format.
```
It seems that loadercdn could not find audio stream from the website provide. Unfortunately it is not something that I can resolve with this wrapper.

**Comment by Jujudo** [comment]
After i downloaded the mp4 there is a video without sound but if you play it on the website there is sound?

**Comment by fredhdx** [comment]
@Jujudo I got the same result even using loaderCDN's online console. It's a server side problem.

I would suspect that the website you provided have uses some techniques to host audio and video at different location, so the current version of loaderCDN cannot correctly parse the result from it. 

Unfortunately this is beyond my capability to fix.
